name: Publish to pub.dev

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
  workflow_dispatch:

jobs:
  publish:
    #runs-on: self-hosted
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
    permissions:
      id-token: write # Required for authentication using OIDC

    